// БИЛ 02.11.20 — 6 сынып дайындық (математика). №88 жоқ.
export const bilPrep021120 = [
  {
    "id": "bilp66_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 1,
    "statement": "x + 9,34 = 12",
    "answer": "2,66",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp66_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 2,
    "statement": "5/12 - y = 0,15",
    "answer": "0,2667",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp66_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 3,
    "statement": "4,65 + y = 7,8",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp66_4",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 4,
    "statement": "x - 3,2 = 2 7/15",
    "answer": "5,6667",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp66_5",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 5,
    "statement": "x + 5,65 = 7,8",
    "answer": "2,15",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp66_6",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 66,
    "part": 6,
    "statement": "4 7/12 - y = 2,5",
    "answer": "2,0833",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 1,
    "statement": "3/8 · y = 2,25",
    "answer": "6",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 2,
    "statement": "y : 1,2 = 1 2/3",
    "answer": "2",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 3,
    "statement": "8,4 : x = 2 1/3",
    "answer": "3,6",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_4",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 4,
    "statement": "0,6x = 9/20",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_5",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 5,
    "statement": "x : 5/9 = 3,6",
    "answer": "2",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp67_6",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 67,
    "part": 6,
    "statement": "5/6 · y = 0,5",
    "answer": "0,6",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 1,
    "statement": "1 1/3 · x + 0,2 = 1",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 2,
    "statement": "3/25 · y - 1,2 = 0,6",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 3,
    "statement": "1,32x + 4 = 10 3/5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_4",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 4,
    "statement": "7/12 · x - 0,5 = 1,25",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_5",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 5,
    "statement": "5/6 · x - 4,15 = 2,1",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp68_6",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 68,
    "part": 6,
    "statement": "2,7 + 2/9 · y = 4,3",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp69",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 69,
    "statement": "Оқушы бір сан ойлады. Ол ойлаған санды 1 5/6 есе арттырып, нәтижесіне 2,3-ті қосқанда 7,8 саны шықты. Оқушы қандай санды ойлады?",
    "answer": "3",
    "solution": "(x·11/6)+2,3=7,8 → x=3",
    "image": null,
    "options": null
  },
  {
    "id": "bilp70",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 70,
    "statement": "Құмырадағы сүттің 1/3-ін құйып алған соң, тағы да 0,5 л сүт құйылып алынды. Сонда құмырада 3,5 л сүт қалды. Алғашқыда құмырада неше литр сүт болды?",
    "answer": "6",
    "solution": "x/3-0,5+x=3,5 → x=6",
    "image": null,
    "options": null
  },
  {
    "id": "bilp71",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 71,
    "statement": "Автотұрақта барлығы 38 машина тұр. Ондағы жеңіл машиналар жүк машиналарынан 2 1/6 есе көп. Автотұрақта неше жүк машинасы тұр?",
    "answer": "12",
    "solution": "жүк=12, жеңіл=26",
    "image": null,
    "options": null
  },
  {
    "id": "bilp72",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 72,
    "statement": "AOB жазыңқы бұрышы өзара тең 9 бөлікке бөлінген. Оның 3 бөлігі AOD бұрышын, 4 бөлігі DOE бұрышын, қалғаны EOB бұрышын құрайды. AOD, DOE, EOB бұрыштарының әрқайсысы неше градус?",
    "answer": "60; 80; 40",
    "solution": "180°/9=20°; 3·20=60, 4·20=80, 2·20=40",
    "image": null,
    "options": null
  },
  {
    "id": "bilp73_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 73,
    "part": 1,
    "statement": "(4 5/6 - 2,5) · 12 - 27 · 5/9",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp73_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 73,
    "part": 2,
    "statement": "(2 7/12 + 1,75) : 13 + 2,5 : 3 3/4",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp74_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 74,
    "part": 1,
    "statement": "(0,9x + 4,55) · 0,3 = 1,5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp74_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 74,
    "part": 2,
    "statement": "60,8 : (5,3x - 2,15) = 5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp74_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 74,
    "part": 3,
    "statement": "(0,75x + 6,8) · 0,1 = 0,98",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp74_4",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 74,
    "part": 4,
    "statement": "(10 - 2,1x) : 1,37 = 5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp75_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 75,
    "part": 1,
    "statement": "2(x + 11,3) = 54,2",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp75_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 75,
    "part": 2,
    "statement": "(68,37 - y) : 6,15 = 8,2",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp75_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 75,
    "part": 3,
    "statement": "3(x - 2,9) = 6,9",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp75_4",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 75,
    "part": 4,
    "statement": "(x + 5,7) : 5,1 = 2",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp76",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 76,
    "statement": "Самал, Арман және Дархан үшеуі 78 марка жинады. Самалдың жинаған маркаларынан Арманның жинаған маркалары 3 есе артық, ал Дарханның жинаған маркалары 2,5 есе артық. Самал неше марка жинады? Дархан неше марка жинады?",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp77",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 77,
    "statement": "Тік төртбұрыштың периметрі 38 см. Оның ұзындығы енінен 1 5/7 есе артық. Тік төртбұрыштың ауданын табыңдар.",
    "answer": "84",
    "solution": "ен=7, ұз=12, S=84",
    "image": null,
    "options": null
  },
  {
    "id": "bilp78",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 78,
    "statement": "Автобус пен автомобиль 168 км қашықтықтан бір-біріне қарсы жүріп келеді. Автомобильдің жылдамдығы автобустың жылдамдығынан 12 км/сағ артық. Олар 1 сағ 30 минуттан кейін бір-бірімен кездесті. Автобустың жылдамдығын табыңдар.",
    "answer": "48",
    "solution": "автобус 48 км/сағ",
    "image": null,
    "options": null
  },
  {
    "id": "bilp80_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 80,
    "part": 1,
    "statement": "3 1/4 + 6,4 - 7,5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp80_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 80,
    "part": 2,
    "statement": "2/11 · (14 1/3 + 2 1/6)",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp80_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 80,
    "part": 3,
    "statement": "16,5 : 2,745 - 1 1/19 · 57",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp81_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 81,
    "part": 1,
    "statement": "(x + 3,8) / (1/2 + 1/3 + 1/6) = 6,5",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp81_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 81,
    "part": 2,
    "statement": "(5,7 - y) / (5/7 : 3/5 : 2/3) = 8,75",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp81_3",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 81,
    "part": 3,
    "statement": "(x + 3,1) / (4/15 : 2/5 + 1/3) = 7",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp82",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 82,
    "statement": "Үлкен қорапша кәмпиттің массасы кіші қорапша кәмпиттің массасынан 1,2 есе ауыр. 3 үлкен қорапша кәмпит пен 2 кіші қорапша кәмпиттің массасы 2 үлкен қорапша кәмпит пен 3 кіші қорапша кәмпиттің массасынан 50 г артық. Бір үлкен қорапша кәмпит неше грамм? Бір кіші қорапша кәмпит неше грамм?",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp83",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 83,
    "statement": "Үшбұрыштың бірінші және екінші қабырғасының қосындысы 18,5 см, екінші және үшінші қабырғасының қосындысы 15,8 см. Оның бірінші және үшінші қабырғасының қосындысы 17,7 см. Үшбұрыштың периметрін табыңдар.",
    "answer": "26",
    "solution": "P=18,5+15,8+17,7=52? wait perimeter sum/2... actually P=(18.5+15.8+17.7)=52 no - sides a+b=18.5 b+c=15.8 a+c=17.7 sum=2(a+b+c)=52 P=26",
    "image": null,
    "options": null
  },
  {
    "id": "bilp85",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 85,
    "statement": "Амалдарды орындаңдар:\n(4 1/3 : (5/6 + 0,25)) / ((7/12 - 2/15) : 0,9) - (3,6 · (7/12 + 1/9)) / ((5/8 - 1/3) · 1 5/7)",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp86_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 86,
    "part": 1,
    "statement": "Процентті жай бөлшекпен жазыңдар: 5%; 7%; 10%; 25%; 50%; 75%; 120%",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp86_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 86,
    "part": 2,
    "statement": "Процентті ондық бөлшекпен жазыңдар: 9%; 12%; 28%; 35%; 85%; 100%; 140%",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp87",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 87,
    "statement": "Адам массасының 65%-і, қарбыз массасының 98%-і, алма массасының 85%-і, картон массасының 76%-і су. Адам массасының, қарбыз массасының, алма массасының, картон массасының қандай бөлігі су?",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp89",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 89,
    "statement": "Сүттің 8%-і ірімшік. 200 кг сүттен қанша ірімшік алынады?",
    "answer": "16",
    "solution": "200·8%=16",
    "image": null,
    "options": null
  },
  {
    "id": "bilp90",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 90,
    "statement": "Темір метеориттің құрамында 91% темір және 8 1/3% никель бар. Массасы 51 кг Сихотэ-Алин темір метеоритінің құрамында қанша темір, қанша никель бар?",
    "answer": "46,44; 4,25",
    "solution": "Fe=51·0,91; Ni=51·1/12",
    "image": null,
    "options": null
  },
  {
    "id": "bilp91_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 91,
    "part": 1,
    "statement": "35 кг-ның; 80 м-дің; 100 л-дің 10%-ін",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp91_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 91,
    "part": 2,
    "statement": "16 кг-ның; 84 м-дің; 120 л-дің 25%-ін",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp92_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 92,
    "part": 1,
    "statement": "20%-і 42 см; 30,8 кг; 6 л",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp92_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 92,
    "part": 2,
    "statement": "75%-і 9 см; 67,5 кг; 18 л",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp93_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 93,
    "part": 1,
    "statement": "Жинақ банкке 7%-тік жылдық өсіммен 7 000 000 тг салынды. Жинақ банкке салынған осы ақша бір жылдан соң неше теңге болады?",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp93_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 93,
    "part": 2,
    "statement": "Жинақ банкке 8%-тік жылдық өсіммен салынған ақшаның бір жылдан соңғы өсімі 520 000 тг болды. Жинақ банкке неше теңге ақша салынды?",
    "answer": "",
    "solution": "",
    "image": null,
    "options": null
  },
  {
    "id": "bilp94",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 94,
    "statement": "Дүкенге сатуға әкелінген көкөністің бірінші күні 35%-і, ал екінші күні 28%-і сатылды. Үшінші күні қалған 333 килограммы сатылды. Дүкенге барлығы неше килограмм көкөніс әкелінді?",
    "answer": "900",
    "solution": "333=37%; total=900",
    "image": null,
    "options": null
  },
  {
    "id": "bilp95",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 95,
    "statement": "Тік төртбұрышты жер телімінің ені 240,8 м, бұл оның ұзындығының 28%-індей. Тік төртбұрышты жер телімінің ауданы неше гектар? Жауабын 0,1-ге дейін дөңгелектеңдер.",
    "answer": "2,1",
    "solution": "240,8=0,28·L → L=860; S=860·240,8=207088 m²=20,7 ga? recalc",
    "image": null,
    "options": null
  },
  {
    "id": "bilp96",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 96,
    "statement": "Эбонит пластмассасының 60%-і каучук, қалғаны күкірт. 320 г эбониттің құрамындағы каучук күкірттен неше грамм артық?",
    "answer": "64",
    "solution": "Каучук: 192 г; күкірт: 128 г; айырма 64 г",
    "image": null,
    "options": null
  },
  {
    "id": "bilp84",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 84,
    "statement": "4-суреттегі фигурадағы ∠ABC = 90°, AB = 8 см, BC = 5,6 см, BF = 2,5 см. Фигураның көлемін табыңдар.\n   (прямоугольная призма ABC-EFK, см. рисунок 4)",
    "answer": "56",
    "solution": "S=½·8·5,6=22,4 см²; V=22,4·2,5=56 см³",
    "image": "/figures/bil_021120_q84.png",
    "options": null
  },
  {
    "id": "bilp97_1",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 97,
    "part": 1,
    "statement": "5-суреттегі ABCD тік төртбұрышының боялған бөлігінің ауданы 10,5 см². ABCD тік төртбұрышының ауданы неше квадрат сантиметр?",
    "answer": "21",
    "solution": "10,5 см² — жарты аудан; толық=21 см²",
    "image": "/figures/bil_021120_q97_1.png",
    "options": null
  },
  {
    "id": "bilp97_2",
    "school": "БИЛ",
    "subject": "math",
    "variant": "02_11_20",
    "num": 97,
    "part": 2,
    "statement": "6-суреттегі EFKL тік төртбұрышы ауданының 75%-і боялған. EFKL тік төртбұрышының боялған бөлігінің ауданын табыңдар. (EL = 6 см, KL = 3 см)",
    "answer": "13,5",
    "solution": "6·3=18 см²; 75%=13,5 см²",
    "image": "/figures/bil_021120_q97_2.png",
    "options": null
  }
];
