import React, { useMemo, useState } from 'react';
import { useLang } from './i18n.jsx';
import { CURRICULUM, createCurriculumQuestions, curriculumAnswersMatch } from './curriculumData.js';
const copies={ru:{eyebrow:'ШКОЛЬНАЯ ПРОГРАММА',title:'Программа 3–6 классов',subtitle:'Разбор каждой темы, примеры и практика по уровню сложности.',grade:'Класс',quarter:'четверть',lessons:'уроков',hours:'ч',standard:'8 уроков в Standard',proAccess:'остальные — Pro',pro:'PRO',upgrade:'Открыть с Pro',back:'К программе',lesson:'РАЗБОР ТЕМЫ',prior:'Что нужно знать заранее',plan:'В этом разборе',explain:'Коротко и понятно',example:'Разберём на примере',rule:'Сначала пойми правило, затем решай. После ответа SYNAQ покажет объяснение.',practice:'Практика',choose:'Настрой тренировку',count:'Количество задач',difficulty:'Сложность',mixed:'Любая',easy:'Лёгкая',medium:'Средняя',hard:'Сложная',start:'Начать',check:'Проверить',next:'Следующая',correct:'Верно!',wrong:'Пока неверно',answer:'Введите ответ',done:'Тренировка завершена',result:'правильных ответов',again:'Ещё раз',list:'Другие темы',soon:'Подробные разборы для этого класса добавляются. Уже сейчас можно посмотреть маршрут тем.'},kk:{eyebrow:'МЕКТЕП БАҒДАРЛАМАСЫ',title:'3–6 сынып бағдарламасы',subtitle:'Әр тақырыпқа түсіндірме, мысал және деңгей бойынша жаттығу.',grade:'Сынып',quarter:'тоқсан',lessons:'сабақ',hours:'сағ',standard:'Standard-та 8 сабақ',proAccess:'қалғаны — Pro',pro:'PRO',upgrade:'Pro арқылы ашу',back:'Бағдарламаға',lesson:'ТАҚЫРЫПТЫ ТАЛДАУ',prior:'Алдын ала нені білу керек',plan:'Бұл талдауда',explain:'Қысқа әрі түсінікті',example:'Мысалмен талдайық',rule:'Алдымен ережені түсін, содан кейін есеп шығар. Жауаптан соң SYNAQ түсіндірмені көрсетеді.',practice:'Жаттығу',choose:'Жаттығуды бапта',count:'Есеп саны',difficulty:'Күрделілік',mixed:'Аралас',easy:'Жеңіл',medium:'Орташа',hard:'Күрделі',start:'Бастау',check:'Тексеру',next:'Келесі',correct:'Дұрыс!',wrong:'Әзірге қате',answer:'Жауапты енгізіңіз',done:'Жаттығу аяқталды',result:'дұрыс жауап',again:'Қайтадан',list:'Басқа тақырыптар',soon:'Бұл сыныптың толық талдаулары дайындалып жатыр. Қазір тақырыптар бағытын көруге болады.'}};

export default function Curriculum({initialGrade,isPro=false,onUpgrade=()=>{}}){
 const {lang}=useLang(),c=copies[lang==='ru'?'ru':'kk'],local=v=>v?.[lang==='ru'?'ru':'kk']||'';
 const reader=lang==='ru'?{contents:'Содержание',intro:'О чём тема',self:'Проверь себя',summary:'Итоги',part:'Часть',of:'из',definition:'Главная мысль',steps:'Решение по шагам',yourTurn:'Теперь попробуй сам',tryHere:'Закрепи эту часть',continue:'Продолжить',previous:'Назад',remaining:'Перед практикой проверь понимание темы.',great:'Отлично — правило понятно.',retry:'Посмотри на пример и попробуй ещё раз.',ready:'Ты разобрал тему',readyText:'Главное правило, пример и проверка пройдены. Теперь закрепи навык задачами разного уровня.'}:{contents:'Мазмұны',intro:'Тақырып туралы',self:'Өзіңді тексер',summary:'Қорытынды',part:'Бөлім',of:'ішінен',definition:'Негізгі ой',steps:'Қадамдық шешім',yourTurn:'Енді өзің орында',tryHere:'Осы бөлімді бекіт',continue:'Жалғастыру',previous:'Артқа',remaining:'Жаттығуға дейін тақырыпты түсінгеніңді тексер.',great:'Өте жақсы — ереже түсінікті.',retry:'Мысалға қарап, қайтадан орындап көр.',ready:'Тақырыпты меңгердің',readyText:'Негізгі ережені, мысалды және тексеруді өттің. Енді дағдыңды әр деңгейдегі есептермен бекіт.'};
 const parsed=Number.parseInt(initialGrade,10);const [grade,setGrade]=useState(parsed>=3&&parsed<=6?parsed:3),[topic,setTopic]=useState(null),[dialog,setDialog]=useState(false),[count,setCount]=useState(5),[level,setLevel]=useState(isPro?'mixed':'easy'),[session,setSession]=useState(null),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(null),[lessonStep,setLessonStep]=useState('intro'),[miniQ,setMiniQ]=useState(null),[miniAnswer,setMiniAnswer]=useState(''),[miniFeedback,setMiniFeedback]=useState(null);
 const gradeTopics=CURRICULUM[grade]||[];
 const grouped=useMemo(()=>[1,2,3,4].map(q=>gradeTopics.filter(t=>t.quarter===q)),[grade]);
 const standardKeys=useMemo(()=>new Set(grouped.flatMap(items=>items.slice(0,2).map(t=>t.key))),[grouped]);
 const canOpen=t=>isPro||standardKeys.has(t.key);
 const begin=()=>{const selectedLevel=isPro?level:'easy',selectedCount=isPro?count:5;setSession({questions:createCurriculumQuestions(topic,selectedLevel,selectedCount),index:0,score:0,finished:false});setAnswer('');setFeedback(null);setDialog(false)};
 const check=()=>{if(!answer.trim()||feedback!==null)return;const ok=curriculumAnswersMatch(answer,session.questions[session.index].answer);setFeedback(ok);if(ok)setSession(s=>({...s,score:s.score+1}))};
 const next=()=>{if(session.index+1>=session.questions.length){setSession(s=>({...s,finished:true}));return}setSession(s=>({...s,index:s.index+1}));setAnswer('');setFeedback(null)};
 const leave=()=>{setTopic(null);setSession(null);setDialog(false);setFeedback(null);setLessonStep('intro')};
 const openTopic=t=>{if(!canOpen(t)){onUpgrade();return}setTopic(t);setLessonStep('intro');setMiniQ(createCurriculumQuestions(t,'easy',1)[0]);setMiniAnswer('');setMiniFeedback(null)};
 const goStep=step=>{setLessonStep(step);if(step==='check'||typeof step==='number'){const difficulty=typeof step==='number'&&step>1?'medium':'easy';setMiniQ(createCurriculumQuestions(topic,difficulty,1)[0]);setMiniAnswer('');setMiniFeedback(null)}};
 if(session&&topic){if(session.finished)return <main className="curriculum-page curriculum-practice-page"><section className="curriculum-result"><span>✓</span><h1>{c.done}</h1><strong>{session.score}/{session.questions.length}</strong><p>{c.result}</p><div><button onClick={begin}>{c.again}</button><button className="ghost" onClick={leave}>{c.list}</button></div></section></main>;const q=session.questions[session.index];return <main className="curriculum-page curriculum-practice-page"><button className="curriculum-back" onClick={()=>setSession(null)}>← {local(topic.title)}</button><section className="curriculum-practice-card"><header><div><span>{c.practice}</span><h1>{local(topic.title)}</h1></div><b>{session.index+1} / {session.questions.length}</b></header><div className="curriculum-practice-track"><i style={{width:`${(session.index+1)/session.questions.length*100}%`}}/></div><p className="curriculum-question">{local(q.text)}</p><input autoFocus inputMode="text" value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')(feedback===null?check():next())}} placeholder={c.answer}/>{feedback!==null&&<div className={`curriculum-feedback ${feedback?'ok':'bad'}`}><b>{feedback?c.correct:c.wrong}</b><p>{local(q.solution)}</p></div>}<button className="curriculum-train" disabled={!answer.trim()} onClick={feedback===null?check:next}>{feedback===null?c.check:c.next} →</button></section></main>}
 if(topic){
  const pages=['intro',...topic.lecture.map((_,i)=>i),'check','summary'];
  const pageIndex=pages.indexOf(lessonStep), chapter=typeof lessonStep==='number'?topic.lecture[lessonStep]:null;
  const advance=()=>goStep(pages[Math.min(pageIndex+1,pages.length-1)]), retreat=()=>goStep(pages[Math.max(pageIndex-1,0)]);
  return <main className="curriculum-page curriculum-detail"><button className="curriculum-back" onClick={leave}>← {c.back}</button><div className="curriculum-reader">
   <nav className="curriculum-reader-nav" aria-label={reader.contents}><strong className="curriculum-reader-nav-title">{reader.contents}</strong>{pages.map((page)=>{const label=page==='intro'?reader.intro:page==='check'?reader.self:page==='summary'?reader.summary:local(topic.lecture[page][0]);return <button key={String(page)} className={lessonStep===page?'on':''} onClick={()=>goStep(page)}><i>{page==='intro'?'·':page==='check'?'?':page==='summary'?'★':page+1}</i><span>{label}</span></button>})}</nav>
   <article className="curriculum-reader-body">
    <div className="curriculum-reader-progress"><i style={{width:`${(pageIndex+1)/pages.length*100}%`}}/></div>
    {lessonStep==='intro'&&<><div className="curriculum-lesson-top"><span>{c.lesson}</span><b>{grade} {c.grade.toLowerCase()} · {topic.hours} {c.hours}</b></div><h1>{local(topic.title)}</h1><p className="curriculum-intro">{local(topic.summary)}</p><section className="curriculum-prior"><span>✓</span><div><b>{c.prior}</b><p>{local(topic.prerequisites)}</p></div></section><h2>{c.plan}</h2><ol className="curriculum-outline">{topic.steps.map((s,i)=><li key={i}><i>{i+1}</i><span>{local(s)}</span></li>)}</ol><div className="curriculum-reader-meta">{reader.part}: {topic.lecture.length} · {c.practice}: {count}</div></>}
    {chapter&&<><div className="curriculum-part-label">{reader.part} {lessonStep+1} {reader.of} {topic.lecture.length}</div><h1>{local(chapter[0])}</h1><section className="curriculum-definition"><span>{reader.definition}</span><p>{local(chapter[1])}</p></section><section className="curriculum-worked"><span>{reader.steps}</span><h3>{c.example}</h3><div className="curriculum-formula">{local(chapter[2])}</div><ol>{topic.steps.map((step,i)=><li key={i}>{local(step)}</li>)}</ol></section><section className="curriculum-chapter-check"><span>{reader.tryHere}</span><p>{local(miniQ?.text)}</p><div><input inputMode="text" value={miniAnswer} onChange={e=>setMiniAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&miniAnswer.trim())setMiniFeedback(curriculumAnswersMatch(miniAnswer,miniQ.answer))}} placeholder={c.answer}/><button disabled={!miniAnswer.trim()} onClick={()=>setMiniFeedback(curriculumAnswersMatch(miniAnswer,miniQ.answer))}>{c.check}</button></div>{miniFeedback!==null&&<aside className={miniFeedback?'ok':'bad'}><b>{miniFeedback?reader.great:reader.retry}</b><small>{local(miniQ.solution)}</small></aside>}</section><section className="curriculum-tip"><span>!</span><p>{c.rule}</p></section></>}
    {lessonStep==='check'&&<><div className="curriculum-part-label">{reader.self}</div><h1>{reader.yourTurn}</h1><p className="curriculum-intro">{reader.remaining}</p><section className="curriculum-mini-check"><p>{local(miniQ?.text)}</p><input inputMode="text" value={miniAnswer} onChange={e=>setMiniAnswer(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&miniAnswer.trim())setMiniFeedback(curriculumAnswersMatch(miniAnswer,miniQ.answer))}} placeholder={c.answer}/><button disabled={!miniAnswer.trim()} onClick={()=>setMiniFeedback(curriculumAnswersMatch(miniAnswer,miniQ.answer))}>{c.check}</button>{miniFeedback!==null&&<div className={miniFeedback?'ok':'bad'}><b>{miniFeedback?reader.great:reader.retry}</b><p>{local(miniQ.solution)}</p></div>}</section></>}
    {lessonStep==='summary'&&<section className="curriculum-reader-summary"><span>✓</span><h1>{reader.ready}</h1><p>{reader.readyText}</p><div>{topic.steps.map((s,i)=><b key={i}>✓ {local(s)}</b>)}</div><button className="curriculum-train" onClick={()=>setDialog(true)}>{c.practice} →</button></section>}
    {lessonStep!=='summary'&&<footer className="curriculum-reader-actions"><button disabled={pageIndex===0} onClick={retreat}>← {reader.previous}</button><button className="primary" onClick={advance}>{reader.continue} →</button></footer>}
   </article>
  </div>{dialog&&<div className="curriculum-modal" role="dialog" aria-modal="true" onMouseDown={e=>{if(e.target===e.currentTarget)setDialog(false)}}><section><button className="curriculum-modal-close" onClick={()=>setDialog(false)}>×</button><span>{c.practice}</span><h2>{c.choose}</h2><label>{c.count}</label><div className="curriculum-counts">{[5,10,15,20].map(n=>{const locked=!isPro&&n>5;return <button className={`${count===n?'on ':''}${locked?'locked':''}`} onClick={()=>locked?onUpgrade():setCount(n)} key={n}>{n}{locked&&<small>PRO</small>}</button>})}</div><label>{c.difficulty}</label><div className="curriculum-levels">{['easy','medium','hard','mixed'].map(v=>{const locked=!isPro&&v!=='easy';return <button className={`${level===v?'on ':''}${locked?'locked':''}`} onClick={()=>locked?onUpgrade():setLevel(v)} key={v}>{c[v]}{locked&&<small>PRO</small>}</button>})}</div><button className="curriculum-train" onClick={begin}>{c.start} →</button></section></div>}</main>
 }
 return <main className="curriculum-page"><header className="curriculum-header"><div><span className="section-eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p>{c.subtitle}</p><div className="curriculum-meta"><b>{gradeTopics.length} {c.lessons}</b><span>{isPro?`${gradeTopics.reduce((n,t)=>n+t.hours,0)} ${c.hours} · 4 ${c.quarter}`:`${c.standard} · ${c.proAccess}`}</span></div></div><div className="curriculum-grade"><span>{c.grade}</span><div>{[3,4,5,6].map(n=><button className={grade===n?'on':''} onClick={()=>{setGrade(n);setTopic(null)}} key={n}>{n}</button>)}</div></div></header><div className="curriculum-quarters">{grouped.map((items,qi)=><section className="curriculum-quarter" key={qi}><div className="curriculum-quarter-title"><span>{String(qi+1).padStart(2,'0')}</span><h2>{qi+1} {c.quarter}</h2><b>{items.reduce((n,t)=>n+t.hours,0)} {c.hours}</b></div><div className="curriculum-topic-list">{items.map((t,i)=>{const open=canOpen(t);return <button className={`curriculum-topic${open?'':' is-locked'}`} onClick={()=>openTopic(t)} aria-label={`${local(t.title)}${open?'':` · ${c.upgrade}`}`} key={t.key}><span>{String(i+1).padStart(2,'0')}</span><div><b>{local(t.title)}</b><small>{local(t.unit)} · {t.hours} {c.hours}</small></div><i>{open?'→':c.pro}</i></button>})}</div></section>)}</div></main>
}
