// Адаптация открытого официального образца NIS, языковой тест (60 заданий).
// Формулировки и тексты нормализованы для интерфейса, ключ ответов сверен с PDF.
// Источник: https://www.nis.edu.kz/storage/files/01JSJ1SCK1WJE5NN8BEKB9B8HX.pdf
const SOURCE = 'NIS official language sample (adapted)';

const q = (num, subject, passage, question, options, correct, solution) => ({
  id: `nis_official_language_2024_${subject}_${String(num).padStart(2, '0')}`,
  school: 'НИШ', subject, topic: `lang_${subject}`, num, difficulty: 2,
  statement: passage ? `${passage}\n\n${question}` : question,
  options, answer: options['ABCD'.indexOf(correct)], solution, source: SOURCE,
});

const ru1 = `По обычаю «Атсүйек беру» воины помогали сарбазу, потерявшему коня в бою: усаживали на своего коня или уступали его, даже рискуя жизнью. Так батыр Ботантай отдал своего коня Абылай хану, когда конь хана пал.`;
const ru2 = `Древние греки отмечали дни рождения богов двенадцать раз в год. Среди простых людей такую привилегию имел только глава семьи — один раз в году. Женщинам и детям особого внимания не уделяли. Позднее дни рождения почти не отмечали: большинство людей не пользовалось календарями, а жизнь отдельного человека мало значила.`;
const ru3 = `Дайвинг позволяет увидеть подводный мир. Учиться можно в бассейне или реке, но морские красоты там не встретишь. На Мальдивах наблюдают морских звёзд, акул и скатов, на Мальте — пещеры и каньоны, у Юкатана — подводные залы со сталактитами. Дайвинг дарит отдых и положительные эмоции.`;
const ru4 = `Если во время еды отвлекаться, человек съедает больше. Исследование показало: участники, игравшие на компьютере или смотревшие телевизор, хуже замечали насыщение и съедали примерно вдвое больше. Поэтому питание не стоит совмещать с такими занятиями.`;
const ru6 = `Девять алматинок приняли участие в фотосессии в стилизованных национальных платьях. Красота камзолов, саукеле и украшений напомнила, как важно чаще обращаться к прошлому и рассказывать о стилях народного костюма.`;
const ru7 = `У разных народов колодцы и родники окружали поверьями. У казахов потомки копателя ежегодно очищали и чинили колодцы. Считалось, что новый колодец зажигает на небе звезду. Колодцам кланялись, давали имена и берегли воду. Загрязнение источника считалось большим грехом.`;
const ru8 = `Учёные опросили 36 тысяч человек, изучая связь музыкальных вкусов с характером. Поклонники классики и тяжёлого рока показали высокий интеллект и оказались творческими, но не очень общительными. Любители рэпа и рэгги продемонстрировали высокую самооценку и коммуникабельность. Результаты опровергли привычные стереотипы.`;
const ru9 = `Исследования показывают, что животные обладают интеллектом. Вороны умеют применять предметы как инструменты, слоны и приматы способны сопереживать. Шимпанзе превосходят людей в некоторых задачах краткосрочной памяти, пчёлы распознают лица, а морские львы логически мыслят. Оценивать интеллект животных нужно объективно.`;
const ru10 = `Кажымукан Мунайтпасов родился в бедной семье в ауле Караоткель. Автор впервые услышала о нём от матери. С детства Мукан отличался огромной силой: легко переносил тяжёлые мешки, побеждал в борьбе. Однажды в буран он погрузил павшую лошадь на сани, вторую привязал сзади и сам дотащил всё до аула. После этого его стали приглашать выступать на тоях, хотя сами победы не приносили ему удовлетворения.`;

const kz21 = `Жас инженерлер жалқауларға арналған ұшатын қоңыраулы сағат ойлап тапты. Қоңырау соғылғанда, тікұшақтікіндей қанаттары айналып, сағат төбеге көтеріледі де, үш минут бойы шырылдайды.`;
const kz22 = `Кітаппен дос болып өскен баланың қиялы ұшқыр болады. Баспа балалар мен ата-аналардың қызығушылығын зерттейді. Қазіргі балалар кітаптары қанық бояумен безендіріліп, панорама және 3D пішінінде жасалады.`;
const kz23 = `Жапонияда Бимо атты ит теледидардан су тасқынын көрген соң үйден кетіп қалады. Кейін иесі оны зардап шеккендерге көмектескен иттерді марапаттау рәсімінен көреді. Үш жылдан соң Бимо үйіне оралады, ал оның ерлігі елге тарайды.`;
const kz25 = `1. Ахмет Жұбанов қазақ күйлерінде табиғаттың үні бар екенін айтқан. 2. Музыка — табиғаттағы сан алуан дыбыстан құралған әуен. 3. Жақсы әуен көңіл күйге және қанайналымға жағымды әсер етеді. 4. Авиценна музыканың емдік қасиетін айтқан. 5. Музыкалық аспапта ойнау қабілетті ашып, шет тілдерін меңгеруге көмектеседі.`;
const kz28 = `Асанәлі Әшімов соғыс жылдарындағы балалық шағын еске алады. Ол аяқкиімсіз мектепке барып, егісте жұмыс істеген. Анасы оны еңбек етуге және білім алуға үйретті. Балалар ойыншықсыз да ойнаған. Актер балаларға жақсы оқып, болашағын ерте ойлауға кеңес береді.`;
const kz33 = `Қарт самурайды ашуландыруға келген жауынгер оған ауыр сөздер айтады, бірақ ұстаз сабағын жалғастыра береді. Самурай: «Қабылданбаған сыйлық өз иесінде қалады. Ашуды да қабылдамасаң, ол айтушыда қалады», — деп түсіндіреді. Демек, сабыр сақтау денсаулықты қорғайды.`;
const kz36 = `Адам қолжуғыштағы сумен және сабынмен жуынып, сүлгімен сүртінеді. Кейін Сүлгі, Қолжуғыш және Сабын адамның тазалығына ең көп үлесті кім қосты деп дауласады. Дау кешке дейін созылады, бірақ су таусылғандықтан ешкім оларға жоламайды.`;
const kz38 = `Қарлығаш әуеде аузын ашып ұшқанда, шыбын-шіркей аузына түседі. Ол қорегін балапандарына әкеледі әрі зиянды жәндіктерді жойып, адамға пайдасын тигізеді. Халық қарлығашты киелі құс санайды.`;
const kz40 = `Қожанасыр досының ескі киім, қағаз және кітаптарды өртемек болғанын көреді. Ол: «Киім ескіреді, бірақ кітаптың сыртқы мұқабасы ғана тозады, ішіндегі ақыл ескірмейді», — дейді.`;

const en41 = `Crystal Cruises offers seven- and fourteen-day Caribbean cruises. Food and drinks are included. Each ship has a casino, cinema, restaurant, theatre, library and gym.`;
const en42 = `School library users may borrow three books and must show their own card. Students should not borrow for friends because the account owner is responsible for lost books. Just as you would not share a computer account, you should not share a library account.`;
const en43 = `Hello Caroline, I teach English to adults in France. Your lessons are fun and very helpful when my students have problems with speaking or writing. I look forward to your future lessons. Best wishes, Christine.`;
const en44 = `1: A two-year music performance contract. 2: A family motel near Stonehenge. 3: Luxury cars for personal hire. 4: Urgent vacancy for a full-time anaesthetist in North London, £50 per hour.`;
const en45 = `Bath is a beautiful city popular with tourists. It has museums, art galleries, Roman Baths, five theatres and several festivals, including music and literature festivals.`;
const en46 = `Choose locally grown food, turn off unused lights and water, and take shorter showers. These actions save water and energy and reduce CO₂ emissions.`;
const en47 = `Nuts contain magnesium, potassium and healthy fats. Although they are high in calories and should be eaten in moderation, they may help lower cholesterol and support heart health.`;
const en48 = `1. People play games, send messages, work and research online. 2. The Internet connects computer networks around the world and gives access to information on remote computers. 3. The number of connected computers and Internet users has grown dramatically since 1981.`;
const en52 = `Victor Davila lives in Hunts Point, where traffic pollutes the air. He founded Eco Ryder: children build skateboards after attending environmental workshops. Victor hopes to expand the project to other cities and involve more young people in their communities.`;
const en55 = `Scientists usually look for new species in remote habitats, so a new frog in New York was surprising. Tests showed that it looked like a leopard frog but had a different blood structure. Its habitat extends across parts of New Jersey and New York. Although it centres near Yankee Stadium, none has yet been found at the stadium.`;
const en58 = `Lila writes that her Pekingese dog Shuga is like a little sister. Her mother brought Shuga home in 2006, and the friendly dog quickly became part of the family. Lila misses Shuga while living on campus and calls her “a girl’s best friend.”`;

export const nishOfficialLanguageQuestions = [
  q(1, 'rus', ru1, 'Почему сарбаз уступал коня воину, оказавшемуся в опасности?', ['Друзья всегда помогают друг другу.', 'Молодые должны почитать старших.', 'Таков был воинский приказ.', 'Таков был закон чести и благородства.'], 'D', 'Обычай описан как проявление отваги, бескорыстия и воинской чести.'),
  q(2, 'rus', ru2, 'Какая информация отсутствует в тексте?', ['Большинство людей обходилось без календарей.', 'В древности люди почитали жизнь каждого человека.', 'Женщины и дети не обладали особыми льготами.', 'Отец семейства мог праздновать день рождения.'], 'B', 'Текст, напротив, сообщает, что жизнь отдельного человека мало значила.'),
  q(3, 'rus', ru3, 'Какова роль перечисления мест для дайвинга по отношению к мысли о красоте подводного мира?', ['Обоснование.', 'Опровержение.', 'Противопоставление.', 'Сравнение.'], 'A', 'Примеры конкретных мест подтверждают мысль первого предложения.'),
  q(4, 'rus', ru4, 'Что в тексте названо «внешними раздражителями»?', ['Громкая музыка.', 'Компьютерная игра и телепередача.', 'Окружающие люди.', 'Запах и вид пищи.'], 'B', 'Именно игра и телевизор отвлекали вторую группу.'),
  q(5, 'rus', ru4, 'Какой вывод лучше завершает текст?', ['Во время игры невозможно считать калории.', 'Не следует совмещать еду с компьютерной игрой или телевизором.', 'Во время просмотра телевизора нужно жевать медленнее.'], 'B', 'Этот вывод прямо следует из результатов исследования.'),
  q(6, 'rus', ru6, 'Какова основная идея текста?', ['Для фотосессии нужны красивые девушки.', 'Национальная одежда — лучшее украшение.', 'В городе нужно всегда носить национальную одежду.', 'Нужно помнить историю национального костюма.'], 'D', 'Финал призывает чаще обращаться к истории костюма.'),
  q(7, 'rus', ru6, 'Выберите грамматически верное продолжение: «невольно думаешь … нужно чаще обращаться к прошлому».', ['над тем, где', 'над тем, как', 'о том, как', 'о том, что'], 'D', 'Нормативная конструкция: «думать о том, что…».'),
  q(8, 'rus', ru7, 'Кто ежегодно очищал колодцы?', ['Потомки того, кто выкопал колодец.', 'Создатели песен.', 'Тот, чьим именем он назван.', 'Только честные люди.'], 'A', 'Это прямо указано в тексте.'),
  q(9, 'rus', ru7, 'Как, согласно поверью, можно было зажечь новую звезду?', ['Выкопать колодец.', 'Дать колодцу имя.', 'Умыться водой.', 'Устроить угощение.'], 'A', 'Новый колодец связывали с появлением новой звезды.'),
  q(10, 'rus', ru7, 'Какова цель текста?', ['Рассказать только об именах колодцев.', 'Описать лечебные свойства воды.', 'Рассказать о поверьях и обычаях разных народов, связанных с источниками.'], 'C', 'Текст объединяет поверья и обычаи нескольких народов.'),
  q(11, 'rus', ru8, 'Какие утверждения верны? 1) Рокеры и любители классики слегка замкнуты. 2) Поклонники рэпа и рэгги общительны.', ['Только 1.', 'Только 2.', 'Оба.', 'Ни одно.'], 'C', 'Оба вывода прямо соответствуют результатам опроса.'),
  q(12, 'rus', ru8, 'Какое слово лучше описывает реакцию учёных на результаты?', ['Возмутили.', 'Обрадовали.', 'Разочаровали.', 'Удивили.'], 'D', 'Результаты оказались неожиданными и разрушили стереотипы.'),
  q(13, 'rus', ru8, 'Что хотел подчеркнуть автор?', ['Рокеры всегда добры.', 'Не стоит слепо доверять стереотипам.', 'Поп-музыка делает трудолюбивым.', 'Тяжёлый рок опасен.'], 'B', 'Исследование показало несостоятельность привычных ярлыков.'),
  q(14, 'rus', ru9, 'Какой миф развеяли исследования?', ['Вороны способны обучаться.', 'Животные думают только о себе.', 'Интеллект животных трудно измерить.', 'У шимпанзе хорошая память.'], 'B', 'Способность животных к сопереживанию опровергает этот миф.'),
  q(15, 'rus', ru9, 'Какова основная мысль текста?', ['Животные иногда превосходят людей.', 'Животные умеют удивлять.', 'Животные сопереживают.', 'Животные обладают способностью мыслить.'], 'D', 'Все примеры подтверждают разные проявления интеллекта животных.'),
  q(16, 'rus', ru9, 'Какова роль заключительной мысли об объективной оценке?', ['Дополнение одного примера.', 'Обобщение всего текста.', 'Опровержение доказательств.', 'Противопоставление информации.'], 'B', 'Заключение суммирует приведённые доказательства.'),
  q(17, 'rus', ru10, 'Откуда автор впервые узнала о Кажымукане?', ['Из рассказов борцов.', 'Из рассказов матери.', 'От аульных аксакалов.', 'От жителей Караоткеля.'], 'B', 'Автор прямо связывает первые рассказы со своей матерью.'),
  q(18, 'rus', ru10, 'Почему Мукана стали приглашать на тои?', ['Он мог съесть барана.', 'Он легко выполнял тяжёлую работу.', 'Он развлекал гостей.', 'Он хотел прославиться.'], 'B', 'История о необычайной силе сделала его известным.'),
  q(19, 'rus', ru10, 'Какие утверждения верны? 1) Кажымукан был из бедной семьи. 2) Он гордился победами.', ['Только 1.', 'Только 2.', 'Оба.', 'Ни одно.'], 'A', 'Первое подтверждается, а победы не приносили ему удовлетворения.'),
  q(20, 'rus', ru10, 'Какова основная цель текста?', ['Рассказать о богатых борцах.', 'Описать прошлое народа.', 'Рассказать, как человек стал легендой.', 'Описать род кыпшаков.'], 'C', 'Текст показывает путь Кажымукана к известности.'),

  q(21, 'kaz', kz21, 'Мәтіндегі сағаттың ерекшелігі неде?', ['Әндетуінде.', 'Батареядан қуат алуында.', 'Кез келген үйде болуында.', 'Қалықтауында.'], 'D', 'Сағаттың басты ерекшелігі — қанаттарының көмегімен төбеге көтерілуі.'),
  q(22, 'kaz', kz22, 'Қай ақпарат дұрыс? 1) Балалар мен ата-аналардың қалауы ескеріледі. 2) Кітаптар түрлі дизайнда шығарылады.', ['Тек біріншісі.', 'Тек екіншісі.', 'Екеуі де дұрыс.', 'Екеуі де бұрыс.'], 'C', 'Мәтінде зерттеу де, түрлі дизайн да аталған.'),
  q(23, 'kaz', kz23, 'Мәтін қандай ит туралы?', ['Жоғалған.', 'Күзетші.', 'Қабаған.', 'Қайырымды.'], 'D', 'Бимо апаттан зардап шеккендерге көмектескен.'),
  q(24, 'kaz', kz23, 'Қай ақпарат мәтін мазмұнына сәйкес келеді?', ['Арнайы ұйым ит туралы ақпаратты жасырды.', 'Бимо иесіне деген адалдығын көрсетті.', 'Бимо жаңалыққа шығу үшін қауіпті жерге барды.', 'Жапондар Бимо туралы ертегі шығарды.'], 'B', 'Бимо үш жылдан кейін өз үйіне оралып, иесіне адалдығын көрсетті.'),
  q(25, 'kaz', kz25, 'Қай абзацта музыкаға түсініктеме беріледі?', ['1', '2', '3', '4'], 'B', 'Екінші ойда музыка табиғи дыбыстардан құралған әуен деп түсіндіріледі.'),
  q(26, 'kaz', kz25, 'Қай ақпарат мәтінге сай келеді?', ['Әуен денсаулыққа әсер ете алады.', 'Музыка тек көңіл көтеруге арналған.', 'Табиғаттағы әр дыбыс емдейді.', 'Тек тілшілер аспапта шебер ойнайды.'], 'A', 'Мәтінде музыканың ағзаға жағымды әсері айтылған.'),
  q(27, 'kaz', kz25, 'Мәтінге қандай тақырып сәйкес келеді?', ['Ғажайып табиғат.', 'Зерттеу алаңы.', 'Музыка құдіреті.', 'Халық аспаптары.'], 'C', 'Барлық абзац музыка әсері мен мүмкіндігін ашады.'),
  q(28, 'kaz', kz28, 'Балалық шақтың қиындығы туралы қай бөлікте айтылады?', ['Соғыс кезіндегі еңбек пен мектеп туралы бөлікте.', 'Анасының мінезі туралы бөлікте.', 'Ойындар туралы бөлікте.', 'Кеңес туралы бөлікте.'], 'A', 'Қиындық соғыс жылдарына арналған алғашқы бөлікте сипатталады.'),
  q(29, 'kaz', kz28, 'Қай тұжырым дұрыс? 1) Балалар жауынгер болып ойнады. 2) Балалар үлкендерге көмектесті.', ['Тек біріншісі.', 'Тек екіншісі.', 'Екеуі де дұрыс.', 'Екеуі де бұрыс.'], 'B', 'Балалардың еңбек еткені айтылады, жауынгер болып ойнағаны айтылмайды.'),
  q(30, 'kaz', kz28, 'Сұхбаттағы тақырыптардың реті қандай?', ['Ойындар, соғыс, оқу, ана.', 'Ойындар, соғыс, ана, оқу.', 'Соғыс, ойындар, ана, оқу.', 'Соғыс, ана, ойындар, оқу.'], 'D', 'Мәтін дәл осы ретпен құрылған.'),
  q(31, 'kaz', kz28, 'Асанәлі Әшімов балаларға қандай кеңес береді?', ['Тек ата-ананың қамқорлығын бағалау.', 'Елдің қамын ғана ойлау.', 'Міндетті түрде ерте еңбек ету.', 'Білім жолында аянбай оқу.'], 'D', 'Оның негізгі кеңесі — оқу және білімді болу.'),
  q(32, 'kaz', kz28, 'Мәтін қандай үлгіде жазылған?', ['Әңгіме.', 'Мақала.', 'Монолог.', 'Сұхбат.'], 'D', 'Мәтін сұрақ-жауап түрінде берілген.'),
  q(33, 'kaz', kz33, 'Жауынгердің өзіндік әдісі қандай?', ['Бәсекелесін ашуландыру.', 'Бәсекелесін қолдау.', 'Сабырлық таныту.', 'Ұстазын құрметтеу.'], 'A', 'Ол қарсыласын ашуландырып, қате жіберуге мәжбүрлейді.'),
  q(34, 'kaz', kz33, 'Қабылданбаған сыйлық кімде қалады?', ['Келген қонақта.', 'Күтіп алушыда.', 'Сыйлық алушыда.', 'Сыйлық берушіде.'], 'D', 'Сыйлықты қабылдамаса, ол берген адамда қалады.'),
  q(35, 'kaz', kz33, 'Қорытындыны бастауға қай сөз лайық?', ['Бірақ.', 'Дегенмен.', 'Демек.', 'Немесе.'], 'C', '«Демек» алдыңғы ойдан қорытынды жасайды.'),
  q(36, 'kaz', kz36, 'Оқиғалардың дұрыс реті қандай?', ['Жуыну → ұзақ дау → Сабын қосылды → Сүлгі мен Қолжуғыш дауласты.', 'Жуыну → Сабын қосылды → ұзақ дау → алғашқы дау.', 'Жуыну → Сүлгі мен Қолжуғыш дауласты → Сабын қосылды → дау созылды.', 'Дау → жуыну → алғашқы дау → Сабын қосылды.'], 'C', 'Оқиға адам жуынғаннан кейін алғашқы дау, Сабынның қосылуы және созылған айтыспен жалғасады.'),
  q(37, 'kaz', kz36, 'Неге кешке дейін ешкім олардың қасына жоламады?', ['Адам дауды тоқтатты.', 'Олар шаршады.', 'Оларды ешкім естімеді.', 'Су таусылып қалды.'], 'D', 'Қолжуғышта су қалмағандықтан, оны ешкім пайдаланбады.'),
  q(38, 'kaz', kz38, 'Қарлығаш қорегін қалай табады?', ['Аузын ашып ұшу арқылы.', 'Тек өте жылдам ұшу арқылы.', 'Балапандарымен бірге аң аулау арқылы.', 'Жәндіктерді жерден теру арқылы.'], 'A', 'Ұшып келе жатқан жәндіктер ашық аузына түседі.'),
  q(39, 'kaz', kz38, 'Мәтін соңында автор неге назар аударады?', ['Адамдардың қамқорлығына.', 'Қарлығаштың адамға пайдасына.', 'Ұя салу қабілетіне.', 'Адамдардың сенгіштігіне.'], 'B', 'Қарлығаш зиянды жәндіктерді жойып, адамға көмектеседі.'),
  q(40, 'kaz', kz40, 'Мәтіннің негізгі ойы қандай?', ['Білім ешқашан тозбайды.', 'Достық ешқашан тозбайды.', 'Киім ешқашан тозбайды.', 'Кітаптың мұқабасы тозбайды.'], 'A', 'Кітаптағы ақыл мен білім ескірмейді.'),

  q(41, 'eng', en41, 'Which statement is correct?', ['The cruise lasts one month.', 'The ships have entertainment areas.', 'Tourists cannot do sport there.', 'Restaurant meals cost extra.'], 'B', 'A cinema, theatre and casino are entertainment areas.'),
  q(42, 'eng', en42, 'Which advice completes the notice?', ['Please avoid sharing your library account.', 'Please always return books early.', 'Please share lunch with classmates.', 'Please change your library account.'], 'A', 'The notice compares the library account with a private computer account.'),
  q(43, 'eng', en43, 'Why does Christine write the letter?', ['She appreciates Caroline’s work.', 'She wants to teach English.', 'She prefers teenagers.', 'She wants to improve her own English.'], 'A', 'She thanks Caroline and explains how useful the lessons are.'),
  q(44, 'eng', en44, 'Which numbered text would help someone searching for work?', ['1', '2', '3', '4'], 'D', 'Text 4 is a vacancy with salary, location and contract details.'),
  q(45, 'eng', en45, 'Where would you most likely find this text?', ['In a holiday advertisement.', 'In a tourist booklet.', 'On a concert invitation.', 'In a TV schedule.'], 'B', 'It introduces a city and its attractions to visitors.'),
  q(46, 'eng', en46, 'What is the main idea?', ['How to lead a healthy lifestyle.', 'How to protect the planet.', 'How to save money.'], 'B', 'Every tip reduces resource use or pollution.'),
  q(47, 'eng', en47, 'Why is a text about nuts titled “Be a Health Nut!”?', ['It helps readers buy nuts.', 'It gives recipes.', 'It explains their health benefits.'], 'C', 'The text focuses on nutrients and heart health.'),
  q(48, 'eng', en48, 'Why does the author begin by asking readers about games and email?', ['To collect answers online.', 'To attract attention to the topic.', 'To make readers search for answers.'], 'B', 'The questions connect everyday experience to the Internet topic.'),
  q(49, 'eng', en48, 'What does “It” refer to in the second part?', ['A computer.', 'An online game.', 'The Internet.'], 'C', 'The preceding subject is the Internet.'),
  q(50, 'eng', en48, 'What is the main idea of the third part?', ['The exact number is impossible to estimate.', 'Connected computers have a rich history.', 'The number of Internet users keeps increasing.'], 'C', 'The figures illustrate rapid growth over time.'),
  q(51, 'eng', en48, 'Which part answers “What is the Internet?”', ['Part 1.', 'Part 2.', 'Part 3.'], 'B', 'Part 2 defines it as a system connecting networks.'),
  q(52, 'eng', en52, 'What does the polluted air in Victor’s neighbourhood show?', ['There are environmental problems.', 'The economy is growing quickly.', 'Too many people share houses.'], 'A', 'Traffic smoke is presented as a local environmental issue.'),
  q(53, 'eng', en52, 'Which phrase best introduces the Bronx River workshop as one example?', ['At least.', 'For example.', 'In addition.', 'On the contrary.'], 'B', 'The river workshop illustrates what children study.'),
  q(54, 'eng', en52, 'What do we learn about Victor’s future plans?', ['He wants to bring the project to other places.', 'He wants to leave environmental work.', 'He cannot interest children.'], 'A', 'His goal is to expand Eco Ryder to other cities.'),
  q(55, 'eng', en55, 'What is the function of the opening part?', ['To list animal habitats.', 'To draw attention to an unusual discovery.', 'To joke about scientists.'], 'B', 'A new species in a large city is presented as unexpected.'),
  q(56, 'eng', en55, 'What distinguishes the new frog from leopard frogs?', ['Its blood structure.', 'Its habitat only.', 'Its appearance.'], 'A', 'The frogs look alike, but their blood structures differ.'),
  q(57, 'eng', en55, 'Which phrase best completes the contrast about Yankee Stadium?', ['But so far.', 'In particular.', 'Once again.'], 'A', '“But so far” contrasts the nearby habitat with the lack of sightings at the stadium.'),
  q(58, 'eng', en58, 'Why did Lila write the post?', ['To complain about campus.', 'To discuss friendship in general.', 'To share her feelings about her pet.'], 'C', 'The whole post expresses her affection for Shuga.'),
  q(59, 'eng', en58, 'Which part explains how Shuga joined the family?', ['Part 1.', 'Part 2.', 'Part 3.'], 'B', 'The second part says Lila’s mother brought Shuga home in 2006.'),
  q(60, 'eng', en58, 'What is the best title?', ['A Day on Campus.', 'A Girl’s Best Friend.', 'A Fashionable Pet.'], 'B', 'The title reflects Lila’s description of Shuga as her closest companion.'),
];
