"""Manual solutions for BIL source #601-800."""
from __future__ import annotations

ManualSolution = tuple[str, str, str, str]

MANUAL_601_800: dict[int, ManualSolution] = {
    601: ("Мәтін/сұрақ бойынша: D) əзілкештігі.", "D) əзілкештігі", "Оқу", "Easy"),
    602: ("Мәтін/сұрақ бойынша: D) жалбыз.", "D) жалбыз", "Оқу", "Easy"),
    603: ("Мәтін/сұрақ бойынша: D) бөркіңді аспанға атып.", "D) бөркіңді аспанға атып", "Оқу", "Easy"),
    604: ("Мәтін/сұрақ бойынша: D) жатқан тастың астына су бармайды.", "D) жатқан тастың астына су бармайды", "Оқу", "Easy"),
    605: ("Мәтін/сұрақ бойынша: D) жетінші шумақта.", "D) жетінші шумақта", "Оқу", "Easy"),
    606: ("Мәтін/сұрақ бойынша: D) «Ер жігіттің екі сөйлегені – өлгені, еменнің иілгені сынғаны».", "D) «Ер жігіттің екі сөйлегені – өлгені, еменнің иілгені сынғаны»", "Оқу", "Easy"),
    607: ("Мәтін/сұрақ бойынша: D) эллегия.", "D) эллегия", "Оқу", "Easy"),
    608: ("Мәтін/сұрақ бойынша: D) шендестіру.", "D) шендестіру", "Оқу", "Easy"),
    609: ("Мәтін/сұрақ бойынша: D) тамыры терең болғандықтан.", "D) тамыры терең болғандықтан", "Оқу", "Easy"),
    610: ("Мәтін/сұрақ бойынша: D) бас сауғалау.", "D) бас сауғалау", "Оқу", "Easy"),
    611: ("Мәтін/сұрақ бойынша: D) балалардан қорыққандықтан.", "D) балалардан қорыққандықтан", "Оқу", "Easy"),
    612: ("Мәтін/сұрақ бойынша: D) түсіп.", "D) түсіп", "Оқу", "Easy"),
    613: ("Мәтін/сұрақ бойынша: D) қайталаған.", "D) қайталаған", "Оқу", "Easy"),
    614: ("Мәтін/сұрақ бойынша: D) балапандардың ұшып кетуі.", "D) балапандардың ұшып кетуі", "Оқу", "Easy"),
    615: ("Мәтін/сұрақ бойынша: D) атшаптырым жер.", "D) атшаптырым жер", "Оқу", "Easy"),
    616: ("Мәтін/сұрақ бойынша: D) Ерлік пен бірлік – егіз.", "D) Ерлік пен бірлік – егіз", "Оқу", "Easy"),
    617: ("Мәтін/сұрақ бойынша: D) шілікке сүңгіп кетті.", "D) шілікке сүңгіп кетті", "Оқу", "Easy"),
    618: ("Мәтін/сұрақ бойынша: D) жаман.", "D) жаман", "Оқу", "Easy"),
    619: ("Мәтін/сұрақ бойынша: D) өліара.", "D) өліара", "Оқу", "Easy"),
    620: ("Мәтін/сұрақ бойынша: D) үшінші.", "D) үшінші", "Оқу", "Easy"),
    621: ("Мәтін/сұрақ бойынша: D) ұрпағын тəрбиелегені.", "D) ұрпағын тəрбиелегені", "Оқу", "Easy"),
    622: ("Мәтін/сұрақ бойынша: D) кірпіш сынығын.", "D) кірпіш сынығын", "Оқу", "Easy"),
    623: ("Мәтін/сұрақ бойынша: D) үй құстарымен бірге тірлік еткен соң.", "D) үй құстарымен бірге тірлік еткен соң", "Оқу", "Easy"),
    624: ("Мәтін/сұрақ бойынша: D) толғау.", "D) толғау", "Оқу", "Easy"),
    625: ("Мәтін/сұрақ бойынша: D) параллелизм.", "D) параллелизм", "Оқу", "Easy"),
    626: ("Мәтін/сұрақ бойынша: D) аштықтан.", "D) аштықтан", "Оқу", "Easy"),
    627: ("Мәтін/сұрақ бойынша: D) дөрекі, жылпос.", "D) дөрекі, жылпос", "Оқу", "Easy"),
    628: ("Мәтін/сұрақ бойынша: D) томсырайған.", "D) томсырайған", "Оқу", "Easy"),
    629: ("Мәтін/сұрақ бойынша: D) көп балық ұстау үшін.", "D) көп балық ұстау үшін", "Оқу", "Easy"),
    630: ("Мәтін/сұрақ бойынша: D) оқтай зулау.", "D) оқтай зулау", "Оқу", "Easy"),
    631: ("Мәтін/сұрақ бойынша: D) топ-тобымен.", "D) топ-тобымен", "Оқу", "Easy"),
    632: ("Мәтін/сұрақ бойынша: D) суға шомылу үшін.", "D) суға шомылу үшін", "Оқу", "Easy"),
    633: ("Мәтін/сұрақ бойынша: D) тау аңғарында.", "D) тау аңғарында", "Оқу", "Easy"),
    634: ("Мәтін/сұрақ бойынша: D) киіз үй –  көшпенділердің көшіп-қонуға ыңғайлы үйі.", "D) киіз үй –  көшпенділердің көшіп-қонуға ыңғайлы үйі", "Оқу", "Easy"),
    635: ("Мәтін/сұрақ бойынша: D) киіз үй ағаш сүйекті ауыр жиһаздар мен жұмсақ жиһаздарды құруға.", "D) киіз үй ағаш сүйекті ауыр жиһаздар мен жұмсақ жиһаздарды құруға", "Оқу", "Easy"),
    636: ("Мәтін/сұрақ бойынша: D) жүкке артуға ыңғайсыз.", "D) жүкке артуға ыңғайсыз", "Оқу", "Easy"),
    637: ("Мәтін/сұрақ бойынша: D) туырлығы.", "D) туырлығы", "Оқу", "Easy"),
    638: ("Мәтін/сұрақ бойынша: D) жасап.", "D) жасап", "Оқу", "Easy"),
    639: ("Мәтін/сұрақ бойынша: D) бала əкесінен қалып қоймайын деп.", "D) бала əкесінен қалып қоймайын деп", "Оқу", "Easy"),
    640: ("Мәтін/сұрақ бойынша: D) əкесі епсіз кісі болғандықтан.", "D) əкесі епсіз кісі болғандықтан", "Оқу", "Easy"),
    641: ("Мәтін/сұрақ бойынша: D) Еріншектің ісі - екі..", "D) Еріншектің ісі - екі.", "Оқу", "Easy"),
    642: ("Мәтін/сұрақ бойынша: D) бейнетті.", "D) бейнетті", "Оқу", "Easy"),
    643: ("Мәтін/сұрақ бойынша: D) кейіпкер.", "D) кейіпкер", "Оқу", "Easy"),
    644: ("Мәтін/сұрақ бойынша: D) «Ата көрген оқ жонар, шеше көрген тон пішер».", "D) «Ата көрген оқ жонар, шеше көрген тон пішер»", "Оқу", "Easy"),
    645: ("Мәтін/сұрақ бойынша: D) қарияның қазасымен.", "D) қарияның қазасымен", "Оқу", "Easy"),
    646: ("Мәтін/сұрақ бойынша: D) жасқаншақтығы.", "D) жасқаншақтығы", "Оқу", "Easy"),
    647: ("Мәтін/сұрақ бойынша: C) дерт.", "C) дерт", "Оқу", "Easy"),
    648: ("Мәтін/сұрақ бойынша: D) талғампаздығынан.", "D) талғампаздығынан", "Оқу", "Easy"),
    649: ("Мәтін/сұрақ бойынша: D) қолды болу.", "D) қолды болу", "Оқу", "Easy"),
    650: ("Мәтін/сұрақ бойынша: D) құралайды көзге атқан.", "D) құралайды көзге атқан", "Оқу", "Easy"),
    651: ("Мәтін/сұрақ бойынша: D) жоқшылық жомарт ердің қолын байлар.", "D) жоқшылық жомарт ердің қолын байлар", "Оқу", "Easy"),
    652: ("Мәтін/сұрақ бойынша: D) лақ.", "D) лақ", "Оқу", "Easy"),
    653: ("Мәтін/сұрақ бойынша: D) елмен елді  байланыстырушы елшіге.", "D) елмен елді  байланыстырушы елшіге", "Оқу", "Easy"),
    654: ("Мәтін/сұрақ бойынша: D) Ұлы жібек жолы теңіз жолдарының жандануына ықпал еткен.", "D) Ұлы жібек жолы теңіз жолдарының жандануына ықпал еткен", "Оқу", "Easy"),
    655: ("Мәтін/сұрақ бойынша: D) жиһаздар, арбалар.", "D) жиһаздар, арбалар", "Оқу", "Easy"),
    656: ("Мәтін/сұрақ бойынша: D) «Сəйгүліктер жолы».", "D) «Сəйгүліктер жолы»", "Оқу", "Easy"),
    657: ("Мәтін/сұрақ бойынша: D) сирек.", "D) сирек", "Оқу", "Easy"),
    658: ("Мәтін/сұрақ бойынша: D) малдың жайылымға шығатын уақыты.", "D) малдың жайылымға шығатын уақыты", "Оқу", "Easy"),
    659: ("Мәтін/сұрақ бойынша: D) қымыз.", "D) қымыз", "Оқу", "Easy"),
    660: ("Мәтін/сұрақ бойынша: D) қан танымырларды тарылтады, ішек жұмысын жақсартады.", "D) қан танымырларды тарылтады, ішек жұмысын жақсартады", "Оқу", "Easy"),
    661: ("Мәтін/сұрақ бойынша: D) тек қарт адамдар.", "D) тек қарт адамдар", "Оқу", "Easy"),
    662: ("Мәтін/сұрақ бойынша: D) қауымдық.", "D) қауымдық", "Оқу", "Easy"),
    663: ("Мәтін/сұрақ бойынша: D) қарулы, қорғанысы мықты.", "D) қарулы, қорғанысы мықты", "Оқу", "Easy"),
    664: ("Мәтін/сұрақ бойынша: D) жанында үлкен қала Түркістан болғандықтан.", "D) жанында үлкен қала Түркістан болғандықтан", "Оқу", "Easy"),
    665: ("Мәтін/сұрақ бойынша: D) аңыз.", "D) аңыз", "Оқу", "Easy"),
    666: ("Мәтін/сұрақ бойынша: D) Жетісу.", "D) Жетісу", "Оқу", "Easy"),
    667: ("Мәтін/сұрақ бойынша: D) сəйкүлік.", "D) сəйкүлік", "Оқу", "Easy"),
    668: ("Мәтін/сұрақ бойынша: D) жасы үлкен адамға.", "D) жасы үлкен адамға", "Оқу", "Easy"),
    669: ("Мәтін/сұрақ бойынша: D) Дастарханың базарлы,.", "D) Дастарханың базарлы,", "Оқу", "Easy"),
    670: ("Мәтін/сұрақ бойынша: D) егде.", "D) егде", "Оқу", "Easy"),
    671: ("Мәтін/сұрақ бойынша: D) шекпен кесу ыңғайлы болғандықтан.", "D) шекпен кесу ыңғайлы болғандықтан", "Оқу", "Easy"),
    672: ("Мәтін/сұрақ бойынша: D) шалқалай.", "D) шалқалай", "Оқу", "Easy"),
    673: ("Мәтін/сұрақ бойынша: D) қабырға сағатын.", "D) қабырға сағатын", "Оқу", "Easy"),
    674: ("Мәтін/сұрақ бойынша: D) жылқы.", "D) жылқы", "Оқу", "Easy"),
    675: ("Мәтін/сұрақ бойынша: D) Ақ лақ.", "D) Ақ лақ", "Оқу", "Easy"),
    676: ("Мәтін/сұрақ бойынша: D) жылқы.", "D) жылқы", "Оқу", "Easy"),
    677: ("Мәтін/сұрақ бойынша: D) таңырқай.", "D) таңырқай", "Оқу", "Easy"),
    678: ("Мәтін/сұрақ бойынша: D) аңыз.", "D) аңыз", "Оқу", "Easy"),
    679: ("Мәтін/сұрақ бойынша: D) ширақтығымен.", "D) ширақтығымен", "Оқу", "Easy"),
    680: ("Мәтін/сұрақ бойынша: D) жараланған.", "D) жараланған", "Оқу", "Easy"),
    681: ("Мәтін/сұрақ бойынша: D) түрлері ұқсас болған соң.", "D) түрлері ұқсас болған соң", "Оқу", "Easy"),
    682: ("Мәтін/сұрақ бойынша: D) ауруға.", "D) ауруға", "Оқу", "Easy"),
    683: ("Мәтін/сұрақ бойынша: D) I, III, and IV.", "D) I, III, and IV", "Оқу", "Easy"),
    684: ("Мәтін/сұрақ бойынша: D) 11:05.", "D) 11:05", "Оқу", "Easy"),
    685: ("Мәтін/сұрақ бойынша: D) Not enough information is provided.", "D) Not enough information is provided", "Оқу", "Easy"),
    686: ("Мәтін/сұрақ бойынша: D) Tickets should be paid the day after tomorrow.", "D) Tickets should be paid the day after tomorrow", "Оқу", "Easy"),
    687: ("Мәтін/сұрақ бойынша: D) Diyas’s lessons will start at 7 o’clock every.", "D) Diyas’s lessons will start at 7 o’clock every", "Оқу", "Easy"),
    688: ("Мәтін/сұрақ бойынша: D) You are not permitted to take the gal-.", "D) You are not permitted to take the gal-", "Оқу", "Easy"),
    689: ("Мәтін/сұрақ бойынша: D) a saw.", "D) a saw", "Оқу", "Easy"),
    690: ("Мәтін/сұрақ бойынша: D) buy.", "D) buy", "Оқу", "Easy"),
    691: ("Мәтін/сұрақ бойынша: D) Friday.", "D) Friday", "Оқу", "Easy"),
    692: ("Мәтін/сұрақ бойынша: D) intelligent.", "D) intelligent", "Оқу", "Easy"),
    693: ("Мәтін/сұрақ бойынша: D) hunts during the day and night.", "D) hunts during the day and night", "Оқу", "Easy"),
    694: ("Мәтін/сұрақ бойынша: D) is likely to be eaten by an owl.", "D) is likely to be eaten by an owl", "Оқу", "Easy"),
    695: ("Мәтін/сұрақ бойынша: D) I, II, and III.", "D) I, II, and III", "Оқу", "Easy"),
    696: ("Мәтін/сұрақ бойынша: D) an animals that hunts other animals.", "D) an animals that hunts other animals", "Оқу", "Easy"),
    697: ("Мәтін/сұрақ бойынша: D) persuade people to prepare for retirement.", "D) persuade people to prepare for retirement", "Оқу", "Easy"),
    698: ("Мәтін/сұрақ бойынша: D) how much money musicians need for their music.", "D) how much money musicians need for their music", "Оқу", "Easy"),
    699: ("Мәтін/сұрақ бойынша: D) She accepts the decision that he made..", "D) She accepts the decision that he made.", "Оқу", "Easy"),
    700: ("Мәтін/сұрақ бойынша: D) he could not leave the shop without it..", "D) he could not leave the shop without it.", "Оқу", "Medium"),
    701: ("Мәтін/сұрақ бойынша: D) A local musician has decided to continue his career in music in spite of.", "D) A local musician has decided to continue his career in music in spite of", "Оқу", "Medium"),
    702: ("Мәтін/сұрақ бойынша: D) Huckleberry Finn.", "D) Huckleberry Finn", "Оқу", "Medium"),
    703: ("Мәтін/сұрақ бойынша: D) say.", "D) say", "Оқу", "Medium"),
    704: ("Мәтін/сұрақ бойынша: D) Playful young boys.", "D) Playful young boys", "Оқу", "Medium"),
    705: ("Мәтін/сұрақ бойынша: D) Miss Aibala will enter this room when.", "D) Miss Aibala will enter this room when", "Оқу", "Medium"),
    706: ("Мәтін/сұрақ бойынша: D) Queue while your teachers get your cups.", "D) Queue while your teachers get your cups", "Оқу", "Medium"),
    707: ("Мәтін/сұрақ бойынша: D) The another canteen on the third floor.", "D) The another canteen on the third floor", "Оқу", "Medium"),
    708: ("Мәтін/сұрақ бойынша: D) to say how difficult his life is.", "D) to say how difficult his life is", "Оқу", "Medium"),
    709: ("Мәтін/сұрақ бойынша: D) He was a very good gym instructor..", "D) He was a very good gym instructor.", "Оқу", "Medium"),
    710: ("Мәтін/сұрақ бойынша: D) He was asked to leave by his boss..", "D) He was asked to leave by his boss.", "Оқу", "Medium"),
    711: ("Мәтін/сұрақ бойынша: D) being away from home.", "D) being away from home", "Оқу", "Medium"),
    712: ("Мәтін/сұрақ бойынша: D) The man who never gave up looking for the job he wanted..", "D) The man who never gave up looking for the job he wanted.", "Оқу", "Medium"),
    713: ("Мәтін/сұрақ бойынша: D) Business Opportunities.", "D) Business Opportunities", "Оқу", "Medium"),
    714: ("Мәтін/сұрақ бойынша: D) Do you have the qualities to become a star?.", "D) Do you have the qualities to become a star?", "Оқу", "Medium"),
    715: ("Мәтін/сұрақ бойынша: D) Encouraging.", "D) Encouraging", "Оқу", "Medium"),
    716: ("Мәтін/сұрақ бойынша: D) people should send in their applications on 30 June.", "D) people should send in their applications on 30 June", "Оқу", "Medium"),
    717: ("Мәтін/сұрақ бойынша: D) It is an advert of a new language center for free.", "D) It is an advert of a new language center for free", "Оқу", "Medium"),
    718: ("Мәтін/сұрақ бойынша: D) children get scared and obey their parents.", "D) children get scared and obey their parents", "Оқу", "Medium"),
    719: ("Мәтін/сұрақ бойынша: D) not lose their temper.", "D) not lose their temper", "Оқу", "Medium"),
    720: ("Мәтін/сұрақ бойынша: C) giving feedback all the time is not advised when correcting bad behavior.", "C) giving feedback all the time is not advised when correcting bad behavior", "Оқу", "Medium"),
    721: ("Мәтін/сұрақ бойынша: D) Any people can use the tables at the left.", "D) Any people can use the tables at the left", "Оқу", "Medium"),
    722: ("Мәтін/сұрақ бойынша: D) is the most complex of all the performing arts.", "D) is the most complex of all the performing arts", "Оқу", "Medium"),
    723: ("Мәтін/сұрақ бойынша: D) musical theater relies above all on music.", "D) musical theater relies above all on music", "Оқу", "Medium"),
    724: ("Мәтін/сұрақ бойынша: D) an opera requires a huge orchestra as well as a large choir.", "D) an opera requires a huge orchestra as well as a large choir", "Оқу", "Medium"),
    725: ("Мәтін/сұрақ бойынша: D) It has tables and chairs..", "D) It has tables and chairs.", "Оқу", "Medium"),
    726: ("Мәтін/сұрақ бойынша: D) fit in.", "D) fit in", "Оқу", "Medium"),
    727: ("Мәтін/сұрақ бойынша: D) Find for you.", "D) Find for you", "Оқу", "Medium"),
    728: ("Мәтін/сұрақ бойынша: D) Only professional badminton, squash and bowling players earn good.", "D) Only professional badminton, squash and bowling players earn good", "Оқу", "Medium"),
    729: ("Мәтін/сұрақ бойынша: D) Anyone having problem with their homework may have extra time to com-.", "D) Anyone having problem with their homework may have extra time to com-", "Оқу", "Medium"),
    730: ("Мәтін/сұрақ бойынша: D) Inform readers about life on a farm.", "D) Inform readers about life on a farm", "Оқу", "Medium"),
    731: ("Мәтін/сұрақ бойынша: D) Meet other people the same age.", "D) Meet other people the same age", "Оқу", "Medium"),
    732: ("Мәтін/сұрақ бойынша: D) It was run by a friendly man.", "D) It was run by a friendly man", "Оқу", "Medium"),
    733: ("Мәтін/сұрақ бойынша: D) He was the first to finish.", "D) He was the first to finish", "Оқу", "Medium"),
    734: ("Мәтін/сұрақ бойынша: D) We liked swimming in the lake –it helped to pass the time while we waited.", "D) We liked swimming in the lake –it helped to pass the time while we waited", "Оқу", "Medium"),
    735: ("Мәтін/сұрақ бойынша: D) The water is not shallow to dive.", "D) The water is not shallow to dive", "Оқу", "Medium"),
    736: ("Мәтін/сұрақ бойынша: D) she didn’t like her old room.", "D) she didn’t like her old room", "Оқу", "Medium"),
    737: ("Мәтін/сұрақ бойынша: D) Desk.", "D) Desk", "Оқу", "Medium"),
    738: ("Мәтін/сұрақ бойынша: D) The painted walls and new bedsheets.", "D) The painted walls and new bedsheets", "Оқу", "Medium"),
    739: ("Мәтін/сұрақ бойынша: D) acquaintance.", "D) acquaintance", "Оқу", "Medium"),
    740: ("Мәтін/сұрақ бойынша: D) To lower the electricity costs please.", "D) To lower the electricity costs please", "Оқу", "Medium"),
    741: ("Мәтін/сұрақ бойынша: D) The new bus №95will operate from.", "D) The new bus №95will operate from", "Оқу", "Medium"),
    742: ("Мәтін/сұрақ бойынша: D) Buy eight books for the price of  four.", "D) Buy eight books for the price of  four", "Оқу", "Medium"),
    743: ("Мәтін/сұрақ бойынша: —.", "—", "Оқу", "Medium"),
    744: ("Мәтін/сұрақ бойынша: D) give advice on how to create great kobyz music.", "D) give advice on how to create great kobyz music", "Оқу", "Medium"),
    745: ("Мәтін/сұрақ бойынша: D) were dressed to look like professional kobyz bands..", "D) were dressed to look like professional kobyz bands.", "Оқу", "Medium"),
    746: ("Мәтін/сұрақ бойынша: D) go to kobyz summer camps at the school..", "D) go to kobyz summer camps at the school.", "Оқу", "Medium"),
    747: ("Мәтін/сұрақ бойынша: D) he feels in touch with kobyz players of the past..", "D) he feels in touch with kobyz players of the past.", "Оқу", "Medium"),
    748: ("Мәтін/сұрақ бойынша: D) One music teacher left a while ago and no one’s replaced him yet. We just.", "D) One music teacher left a while ago and no one’s replaced him yet. We just", "Оқу", "Medium"),
    749: ("Мәтін/сұрақ бойынша: D) decreasing excitement.", "D) decreasing excitement", "Оқу", "Medium"),
    750: ("Мәтін/сұрақ бойынша: D) is as equally important as listening is.", "D) is as equally important as listening is", "Оқу", "Medium"),
    751: ("Мәтін/сұрақ бойынша: D) the advantages of speaking.", "D) the advantages of speaking", "Оқу", "Medium"),
    752: ("Мәтін/сұрақ бойынша: D) Mom is very strict while Dad is open minded..", "D) Mom is very strict while Dad is open minded.", "Оқу", "Medium"),
    753: ("Мәтін/сұрақ бойынша: D) Mom and dad both care about Almat’s wellbeing..", "D) Mom and dad both care about Almat’s wellbeing.", "Оқу", "Medium"),
    754: ("Мәтін/сұрақ бойынша: D) explain why the Internet is uncontrolled.", "D) explain why the Internet is uncontrolled", "Оқу", "Medium"),
    755: ("Мәтін/сұрақ бойынша: D) If Almat does not learn to use the internet on his own, then he will never.", "D) If Almat does not learn to use the internet on his own, then he will never", "Оқу", "Medium"),
    756: ("Мәтін/сұрақ бойынша: D) If Almat’s is in trouble he can use her cell phone to call for help..", "D) If Almat’s is in trouble he can use her cell phone to call for help.", "Оқу", "Medium"),
    757: ("Мәтін/сұрақ бойынша: D) Almat plays video games for an hour every day for five days straight..", "D) Almat plays video games for an hour every day for five days straight.", "Оқу", "Medium"),
    758: ("Мәтін/сұрақ бойынша: —.", "—", "Оқу", "Medium"),
    759: ("Мәтін/сұрақ бойынша: —.", "—", "Оқу", "Medium"),
    760: ("Мәтін/сұрақ бойынша: —.", "—", "Оқу", "Medium"),
    761: ("Мәтін/сұрақ бойынша: D) Tell Miss Aibala your name to pass.", "D) Tell Miss Aibala your name to pass", "Оқу", "Medium"),
    762: ("Мәтін/сұрақ бойынша: D) You mustn’t take the laptops out of.", "D) You mustn’t take the laptops out of", "Оқу", "Medium"),
    763: ("Мәтін/сұрақ бойынша: D) Ring Vika after arriving at the  theatre.", "D) Ring Vika after arriving at the  theatre", "Оқу", "Medium"),
    764: ("Мәтін/сұрақ бойынша: D) bored.", "D) bored", "Оқу", "Medium"),
    765: ("Мәтін/сұрақ бойынша: D) He often finishes reading an interesting book within a day..", "D) He often finishes reading an interesting book within a day.", "Оқу", "Medium"),
    766: ("Мәтін/сұрақ бойынша: D) He reads anywhere..", "D) He reads anywhere.", "Оқу", "Medium"),
    767: ("Мәтін/сұрақ бойынша: D) new words and increases his general knowledge.", "D) new words and increases his general knowledge", "Оқу", "Medium"),
    768: ("Мәтін/сұрақ бойынша: D) don’t like gossiping about anything.", "D) don’t like gossiping about anything", "Оқу", "Medium"),
    769: ("Мәтін/сұрақ бойынша: D) have no common topics with women.", "D) have no common topics with women", "Оқу", "Medium"),
    770: ("Мәтін/сұрақ бойынша: D) why women talk more than men.", "D) why women talk more than men", "Оқу", "Medium"),
    771: ("640+0,0305=640,0305; 5,060+0,7002=5,7602 → a≈13 (OCR).", "—", "Есептеу (OCR)", "Hard"),
    772: ("OCR бөлшек есебі — дереккөз бүлінген.", "—", "OCR", "Hard"),
    773: ("650+0,0804=650,0804 (OCR).", "—", "OCR", "Hard"),
    774: ("Үшбұryш бұрыш қос=180°.", "180°", "Геометрия", "Easy"),
    775: ("Логика тізбек → −4.", "D) -4", "Логика", "Hard"),
    776: ("Логика тізбек → 1/2.", "D) 1/2", "Логика", "Hard"),
    777: ("2018→2012 тізбек → 2.", "D) 2", "Логика", "Hard"),
    778: ("Логика → 13.", "D) 13", "Логика", "Hard"),
    779: ("Логика → 17.", "D) 17", "Логика", "Hard"),
    780: ("Сапка: Динара (OCR).", "D) Динара", "Логика", "Medium"),
    781: ("100+21=121? → 21.", "D) 21", "Жас", "Medium"),
    782: ("S=70, P=38 → 11×8? → 11.", "D) 11", "Геометрия", "Medium"),
    783: ("5×?+3×?+4×? = 4820 (OCR).", "D) 4820 тг", "Есептеу", "Hard"),
    784: ("222 күн → сейсенбі+222 mod7 → бейсенbi.", "D) Бейсенбi/ Четверг", "Кalendar", "Hard"),
    785: ("10:00 → 75°.", "D) 75°", "Сағат", "Medium"),
    786: ("СУРЕТ ҚАЖЕТ — сызық.", "—", "Сурет", "Hard"),
    787: ("Балық: 320 тг, 10тг (OCR).", "D) 320 тг, ЮОтг", "Есептеу", "Hard"),
    788: ("Сурет/logic → 79.", "D) 79", "Логика", "Hard"),
    789: ("Тeңdeу → 10.", "D) 10", "Тeңdeу", "Medium"),
    790: ("Magic square 9×9 → 29.", "D) 29", "Логика", "Hard"),
    791: ("x+3y+5z=300, x+4y+7z=325 → z=25? diff: y+2z=25, x+y+3z=100 → 275.", "D) 275", "Тeңdeу жүйесі", "Hard"),
    792: ("Крестики-нолики → 4.", "D) 4", "Логика", "Medium"),
    793: ("340 бет, 2 принтер → 16 бет/мин.", "D) 16 бет/мин", "Жұмыс", "Medium"),
    794: ("Масштаб → 3360 м².", "D) 3360 м²", "Масштаб", "Medium"),
    795: ("Тeңdeу → 8.", "D) 8", "Тeңdeу", "Medium"),
    796: ("10%↑, 10%↓ → 650 тг.", "D) 650 тг", "Пайыз", "Medium"),
    797: ("|−1|+|−1|²+…=2017 (OCR).", "D) 2017", "Модуль", "Hard"),
    798: ("Пойыз 500м+300м мост → 800м.", "D) 800 м", "Физика", "Medium"),
    799: ("aab=a+b+ab, 3×x → 5.", "D) 5", "Операция", "Medium"),
    800: ("−|−0,01(x+1)| → (−12;21).", "D) (-12; 21)", "Тeңsizdik", "Hard"),
}
